# API Article
@host = http://localhost:3000/api/article
###
GET {{host}}
###
POST {{host}}
content-type: application/json

{
  "title": "First article"
}
###
GET {{host}}/1
###
PATCH {{host}}/1
content-type: application/json

{
  "title": "Updated article"
}
###
DELETE {{host}}/1
