# API User

@host = http://localhost:3000/api/user

GET {{host}}

###

POST {{host}}
content-type: application/json

{
  "username": "John"
}

###

GET {{host}}/1

###

PATCH {{host}}/1
content-type: application/json

{
  "username": "Bob"
}

###

DELETE {{host}}/1
