# API User

@host = http://localhost:3000/api/user

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTIwNTM2MTg1fQ.im_Eufe7xbr8ZX2wYA6YTCwSyOubzCmQhTNLneA1n-I
GET {{host}}

###

POST {{host}}
content-type: application/json

{
  "username": "John"
}

###

GET {{host}}/1

###

PATCH {{host}}/1
content-type: application/json

{
  "username": "Bob"
}

###

DELETE {{host}}/1

###

GET {{host}}/me
content-type: application/json
Authorization: Bearer {{token}}
